### ISSUE TITLE
this code contains errors in AP3216_Basics

### ISSUE THREAD

**Issue by yva2311** [igorantolic/ai_ap3216_ambient-light-and-proximity-sensor-library#1]
`Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\USERNAME\Documents\Arduino\libraries\ai_ap3216_ambient-light-and-proximity-sensor-library-master\src\Ai_AP3216_AmbientLightAndProximity.cpp: In member function 'void Ai_AP3216_AmbientLightAndProximity::begin()':

C:\Users\USERNAME\Documents\Arduino\libraries\ai_ap3216_ambient-light-and-proximity-sensor-library-master\src\Ai_AP3216_AmbientLightAndProximity.cpp:35:30: error: no matching function for call to 'TwoWire::begin(int&, int&)'

   Wire.begin(pin_sda, pin_scl);

                              ^

C:\Users\USERNAME\Documents\Arduino\libraries\ai_ap3216_ambient-light-and-proximity-sensor-library-master\src\Ai_AP3216_AmbientLightAndProximity.cpp:35:30: note: candidates are:

In file included from C:\Users\USERNAME\Documents\Arduino\libraries\ai_ap3216_ambient-light-and-proximity-sensor-library-master\src\Ai_AP3216_AmbientLightAndProximity.h:11:0,

                 from C:\Users\USERNAME\Documents\Arduino\libraries\ai_ap3216_ambient-light-and-proximity-sensor-library-master\src\Ai_AP3216_AmbientLightAndProximity.cpp:5:

C:\Users\USERNAME\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src/Wire.h:52:10: note: void TwoWire::begin()

     void begin();

          ^

C:\Users\USERNAME\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src/Wire.h:52:10: note:   candidate expects 0 arguments, 2 provided

C:\Users\USERNAME\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src/Wire.h:53:10: note: void TwoWire::begin(uint8_t)

     void begin(uint8_t);

          ^

C:\Users\USERNAME\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src/Wire.h:53:10: note:   candidate expects 1 argument, 2 provided

C:\Users\USERNAME\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src/Wire.h:54:10: note: void TwoWire::begin(int)

     void begin(int);

          ^

C:\Users\USERNAME\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src/Wire.h:54:10: note:   candidate expects 1 argument, 2 provided

C:\Users\USERNAME\Documents\Arduino\libraries\ai_ap3216_ambient-light-and-proximity-sensor-library-master\src\Ai_AP3216_AmbientLightAndProximity.cpp: In member function 'int Ai_AP3216_AmbientLightAndProximity::AP3216_read(int)':

C:\Users\USERNAME\Documents\Arduino\libraries\ai_ap3216_ambient-light-and-proximity-sensor-library-master\src\Ai_AP3216_AmbientLightAndProximity.cpp:131:54: error: call of overloaded 'requestFrom(uint8_t&, size_t, bool)' is ambiguous

  Wire.requestFrom(AP3216_iic_address, (size_t)1, true);

                                                      ^

C:\Users\USERNAME\Documents\Arduino\libraries\ai_ap3216_ambient-light-and-proximity-sensor-library-master\src\Ai_AP3216_AmbientLightAndProximity.cpp:131:54: note: candidates are:

In file included from C:\Users\USERNAME\Documents\Arduino\libraries\ai_ap3216_ambient-light-and-proximity-sensor-library-master\src\Ai_AP3216_AmbientLightAndProximity.h:11:0,

                 from C:\Users\USERNAME\Documents\Arduino\libraries\ai_ap3216_ambient-light-and-proximity-sensor-library-master\src\Ai_AP3216_AmbientLightAndProximity.cpp:5:

C:\Users\USERNAME\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src/Wire.h:62:13: note: uint8_t TwoWire::requestFrom(uint8_t, uint8_t, uint8_t)

     uint8_t requestFrom(uint8_t, uint8_t, uint8_t);

             ^

C:\Users\USERNAME\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src/Wire.h:65:13: note: uint8_t TwoWire::requestFrom(int, int, int)

     uint8_t requestFrom(int, int, int);

             ^

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by igorantolic** [comment]
Fix for Arduino UNO
Some functions were used which doesnt exists for Arduino.
Can you try with newer version?

**Comment by yva2311** [comment]
The light sensor works (**Thank You !!!**), but the proximity sensor shows "0-25", and in sample "DetectCloseObject" in serial port i don't see  anything.
