### ISSUE TITLE
ESP32 error

### ISSUE THREAD

**Issue by chaffinched** [igorantolic/ai_ap3216_ambient-light-and-proximity-sensor-library#3]
Hi, this works fine on an ESP8266 / Wemos D1 mini (thanks!) but on a generic ESP32 (ESP-WROOM-32 DEVKIT) I got an error from the Arduino IDE that "Wire.requestFrom(AP3216_iic_address, (size_t)1, true);" was ambiguous on line 137 of the .cpp file. 

I'm not a programmer, so I've got no idea whether this was a valid or right thing to do, but removing "|| defined(ESP32)" from line 136 got it working for me.

**Comment by vvs551** [comment]
Line 6 should be for ESP32:
uint16_t AP3216_iic_address ;// I2C Address of AP3216 sensor is 0x1E

**Comment by chaffinched** [comment]
Thanks. Unable to test now, so I'll close the ticket.
